baseURL = "https://github.com/karin-romero/static_website/"
languageCode = "en-us"
title = "MSIG XXI - My New Hugo Site"
publishDir = "docs"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
